from __future__ import annotations

"""SQLAlchemy MetaData and Table definitions for OpenKB Phase 0.

This module is the single source of truth for the database schema.  All
services and tests import the Table objects from here — never re-define
columns elsewhere.

Tables created by migration 0001_phase0_initial_schema:
- knowledge_bases
- documents
- wiki_pages
"""

from sqlalchemy import (
    Boolean,
    Column,
    ForeignKey,
    Integer,
    MetaData,
    Table,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.sql import text
from sqlalchemy.types import TIMESTAMP

metadata = MetaData()

# ---------------------------------------------------------------------------
# compiler_jobs
# Postgres-backed FIFO job queue (replaces Redis BRPOP).
# Enqueued by the API/ingest layer; claimed via SELECT … FOR UPDATE SKIP LOCKED.
# ---------------------------------------------------------------------------
compiler_jobs = Table(
    "compiler_jobs",
    metadata,
    Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    ),
    Column(
        "kb_id",
        UUID(as_uuid=True),
        ForeignKey("knowledge_bases.id"),
        nullable=False,
    ),
    Column(
        "document_id",
        UUID(as_uuid=True),
        ForeignKey("documents.id"),
        nullable=False,
    ),
    Column("blob_path", Text, nullable=False),
    Column("filename", Text, nullable=False),
    Column("status", Text, nullable=False, server_default=text("'pending'")),
    Column(
        "enqueued_at",
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    ),
    Column("claimed_at", TIMESTAMP(timezone=True), nullable=True),
    Column("worker_id", Text, nullable=True),
)

# ---------------------------------------------------------------------------
# knowledge_bases
# Root container for a compilation project.
# ---------------------------------------------------------------------------
knowledge_bases = Table(
    "knowledge_bases",
    metadata,
    Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    ),
    Column("name", Text, nullable=False),
    Column("slug", Text, nullable=False, unique=True),
    Column("description", Text, nullable=True),
    Column("storage_container_path", Text, nullable=True),
    Column(
        "git_versioning_enabled",
        Boolean,
        nullable=False,
        server_default=text("TRUE"),
    ),
    # JSONB stores {language, pageindex_threshold, entity_types, extra_headers}.
    # Shape validation is the responsibility of the application layer.
    Column("compilation_config", JSONB, nullable=True),
    # TEXT not ENUM — avoids painful ALTER TYPE migrations when values extend.
    # Allowed: "active", "archived" — enforced by the service layer.
    Column("status", Text, nullable=False),
    Column(
        "created_at",
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    ),
    Column(
        "updated_at",
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    ),
    # Soft-delete: NULL means the row is not deleted.
    Column("deleted_at", TIMESTAMP(timezone=True), nullable=True),
)

# ---------------------------------------------------------------------------
# documents
# A source artefact ingested into a KnowledgeBase.
# ---------------------------------------------------------------------------
documents = Table(
    "documents",
    metadata,
    Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    ),
    # Indexed for efficient lookups by KB (FR-006).
    Column(
        "kb_id",
        UUID(as_uuid=True),
        ForeignKey("knowledge_bases.id"),
        nullable=False,
        index=True,
    ),
    # e.g. "pdf", "docx", "pptx", "xlsx", "html", "md", "csv", "url", "text"
    Column("source_type", Text, nullable=False),
    Column("source_uri", Text, nullable=True),
    Column("original_filename", Text, nullable=True),
    # TEXT not ENUM. Allowed: "pending", "compiling", "complete", "failed".
    Column("status", Text, nullable=False),
    Column("failure_reason", Text, nullable=True),
    Column("pageindex_used", Boolean, nullable=True),
    Column("token_cost", Integer, nullable=True),
    Column(
        "created_at",
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    ),
    Column(
        "updated_at",
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    ),
    Column("deleted_at", TIMESTAMP(timezone=True), nullable=True),
)

# ---------------------------------------------------------------------------
# wiki_pages
# A compiled output page generated by the OpenKB engine.
# ---------------------------------------------------------------------------
wiki_pages = Table(
    "wiki_pages",
    metadata,
    Column(
        "id",
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    ),
    # Indexed for efficient lookups by KB (FR-006).
    Column(
        "kb_id",
        UUID(as_uuid=True),
        ForeignKey("knowledge_bases.id"),
        nullable=False,
        index=True,
    ),
    # e.g. "summary", "concept", "entity", "index", "exploration"
    Column("page_type", Text, nullable=False),
    Column("slug", Text, nullable=False),
    Column("blob_path", Text, nullable=True),
    # For entity pages: "person", "organization", "place", etc.
    Column("entity_type", Text, nullable=True),
    Column("last_compiled_at", TIMESTAMP(timezone=True), nullable=True),
    Column(
        "created_at",
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    ),
    Column(
        "updated_at",
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=text("NOW()"),
    ),
    Column("deleted_at", TIMESTAMP(timezone=True), nullable=True),
    # Composite unique: slug is unique within a KB (FR-005).
    UniqueConstraint("kb_id", "slug", name="uq_wiki_pages_kb_id_slug"),
)

__all__ = ["metadata", "knowledge_bases", "documents", "wiki_pages", "compiler_jobs"]
